### ISSUE TITLE
Is there any way to terminate close to a desired number of function evaluations?

### ISSUE THREAD

**Issue by microprediction** [Stefan-Endres/shgo#34]
I've noticed that {'maxfev':50} often results in >200 actual function evaluations. Is there a way to ensure this number is closer to what one desires, for example when the function to be evaluated is very expensive?

**Comment by alchemyst** [comment]
This is probably due to the extra function evaluations used by the local minimisation. You can try to pass a low `maxiter` value in `minimizer_kwargs`.

**Comment by microprediction** [comment]
Thanks that helps somewhat.

**Comment by Stefan-Endres** [comment]
In addition to supplying `minimizer_kwargs` (only supported by some local solvers), there is also a bug in the current stable release that incorrectly runs an entire extra global iteration under some circumstances. This should be fixed with ea62d2f2a22024149624d315d08eff0c8ad33c1c and will be added to added to downstream repositories (scipy and pypi) once the last unittests are fixed (failures related to another issue).
